### ISSUE TITLE
can't find BrawlLib

### ISSUE THREAD

**Issue by Tcll** [libertyernie/brawltools#185]
![](https://cdn.discordapp.com/attachments/257606274357788672/457568810585554975/unknown.png)

this has been happening ever since the `Lib/` folder was introduced.

**Comment by libertyernie** [comment]
Looks like wine is having trouble reading the BrawlBox.exe.config file. I can think of a few quick workarounds you could try:

* Get rid of the Lib folder and move everything to the same folder as BrawlBox.exe
* Try using mono instead of wine
* Try using StageBox (https://github.com/soopercool101/stagebox) instead of BrawlBox

**Comment by Tcll** [comment]
oh that's interesting...
I created this issue because I'd done the removal of the Lib folder before, but Brbx complained about it "Missing Lib directory" or something...
looks like that's working now... cool

as for mono, I have grievances with that as it seems to be very unstable...
there's certain cases it'll work seemingly well, but others where it'll crash by expanding a tree... heh

thanks for getting me to try to get a shot of that "Missing Lib directory" dialog XD
