### ISSUE TITLE
getting "unable to cast object type 'Brawl Lib.SSBB..." error

### ISSUE THREAD

**Issue by nanogram** [libertyernie/brawltools#194]
I get this error when I try to edit home_eng.pac file for ssbb, its in files/system/homebutton

**Comment by libertyernie** [comment]
Can you either copy/paste the error or post a screenshot?
If not, I might be able to take a look at some point.

**Comment by libertyernie** [comment]
That shrinking problem is a known issue when using a high-DPI display. I've never figured out how to fix it.

**Comment by nanogram** [comment]
Yeah, I’m using a 4K laptop screen. But I also used a 1080 screen in the past and had the same issue with shrinking...

**Comment by soopercool101** [comment]
> That shrinking problem is a known issue when using a high-DPI display. I've never figured out how to fix it.

In case you're curious, the issue is on the first line of the LoadImagesPreservingPaletteInfo function. Makes no sense to me as of why that would be the case, and the only way I've found of fixing it is removing the palette preservation functionality entirely, but I know it's that line that causes the resize according to those who experience that glitch.

**Comment by libertyernie** [comment]
Nice tip. Also, it looks like even after removing LoadImagesPreservingPaletteInfo, I can still import palettes from indexed PNG files. Maybe GDI supports it now?

**Comment by soopercool101** [comment]
From what I've seen, removing that function removes color smash support (the new method in which CSS portraits are made to share an image with different palettes), though I may be mistaken
