### ISSUE TITLE
Attached texture doesn't import properly into Brawlbox

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#79]
The included texture (AssassinBody_Diff.tga) doesn't show up properly in Brawlbox.

[AssassinBody_Diff.zip](https://github.com/libertyernie/brawltools/files/522309/AssassinBody_Diff.zip)

![photoshopvsbrawlbox](https://cloud.githubusercontent.com/assets/17330088/19277905/6003b688-8fa9-11e6-8ea7-811eeddb13f5.PNG)

**Comment by libertyernie** [comment]
This file doesn't look right in GIMP, either - looks like the alpha channel is the opposite of what it should be (which is why it's all transparent except for the blue part in the lower left.) It might be possible to add a feature that swaps the alpha channels, but it seems strange that Photoshop would export it like that.

I have an old copy of Photoshop at home - I'll take a look later.

**Comment by libertyernie** [comment]
I added a couple of commits that allow the user to swap alpha in the texture converter, and hopefully it'll auto-detect images like this and have that checkbox checked for you.
